const drugs=[['Cocaine','⚪',1200,9000],['Crack','🪨',800,5200],['Ecstasy','🟢',200,2800],['Hashish','🧱',300,2500],['Heroin','💉',900,6000],['Ice','💎',700,4200],['Kat','🌿',40,800],['LSD','🎟️',120,1600],['MDA','🟣',200,1800],['Morphine','🧴',500,2600],['Mushrooms','🍄',60,900],['Peyote','🌵',80,1200],['Pot','🍃',80,900],['Speed','▱',160,1800]];
const places=[['London','UK','🇬🇧','Heathrow / City'],['Manchester','UK','🇬🇧','Manchester Airport'],['Birmingham','UK','🇬🇧','BHX'],['Liverpool','UK','🇬🇧','John Lennon'],['Leeds','UK','🇬🇧','Leeds Bradford'],['Newcastle','UK','🇬🇧','NCL'],['Bristol','UK','🇬🇧','Bristol Airport'],['Cardiff','Wales','🏴','Cardiff Airport'],['Glasgow','Scotland','🏴','GLA'],['Edinburgh','Scotland','🏴','EDI'],['Aberdeen','Scotland','🏴','ABZ'],['Belfast','Northern Ireland','🇬🇧','BFS'],['Dublin','Ireland','🇮🇪','DUB'],['Cork','Ireland','🇮🇪','ORK']];
const lenders=[['SPAMMER',10000,3,.25],['TOMMY',20000,5,.30],['SMUDGER',50000,5,.50],['BAZZER',75000,3,.50],['GRIFF',100000,3,.70]];
const shopItems=[['Large Coat',100,50,'person'],['Backpack',50,75,'person'],['Shed',500,250,'offsite'],['Lockup',5000,1000,'offsite'],['Warehouse',25000,50000,'offsite']];
const weapons=[['Small Knife',50,.10],['Machete',100,.30],['Handgun',500,.60]];
const attackers=[['single addict',.36,2,.25],['small group of lads',.31,10,.35],['small gang',.22,20,.50],['large gang',.11,50,.75]];
const $=id=>document.getElementById(id), money=n=>'£'+Math.round(n).toLocaleString('en-GB'), rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, pick=a=>a[rand(0,a.length-1)], pickDrug=()=>pick(drugs)[0];
let s;
function blankInv(){return Object.fromEntries(drugs.map(d=>[d[0],0]))}
function blankSupply(){return Object.fromEntries(drugs.map(d=>[d[0],rand(0,1000)]))}
function baseState(){return{day:1,maxDay:30,cash:1000,bank:0,debt:0,health:100,heat:0,city:0,inv:blankInv(),supply:blankSupply(),prices:{},trends:{},owned:[],weapons:[],loans:[],rumour:null,notice:'You start in London with £1,000 cash, £0 in the bank and a clean slate.'}}
function totalSpace(){return 20+s.owned.reduce((a,n)=>a+(shopItems.find(i=>i[0]===n)?.[2]||0),0)}
function personSpace(){return 20+s.owned.reduce((a,n)=>a+((shopItems.find(i=>i[0]===n)?.[3]==='person')?(shopItems.find(i=>i[0]===n)[2]):0),0)}
function used(){return Object.values(s.inv).reduce((a,b)=>a+b,0)}
function rank(){let worth=s.cash+s.bank+Object.entries(s.inv).reduce((a,[k,v])=>a+v*(s.prices[k]||0),0)-s.debt; if(worth>500000)return'kingpin'; if(worth>150000)return'operator'; if(worth>50000)return'supplier'; if(worth>10000)return'runner'; return'wannabe'}
function genPrices(force){let target=force?.rumour?.drug; drugs.forEach(([name,,lo,hi])=>{let old=s.prices[name]||rand(lo,hi); let mult=rand(55,155)/100; if(force&&force.true&&name===target) mult=force.rumour.type==='scarce'?rand(170,320)/100:rand(20,55)/100; let p=Math.max(1,Math.round(((old+rand(lo,hi))/2)*mult)); s.trends[name]=p>=old; s.prices[name]=p; s.supply[name]=rand(0,1000); if(force&&force.true&&name===target&&force.rumour.type==='scarce')s.supply[name]=rand(0,90); if(force&&force.true&&name===target&&force.rumour.type==='abundant')s.supply[name]=rand(600,1000);});}
function cityText(){let city=places[s.city][0]; let lines={London:['club demand is moving through central London','airport heat is visible around Heathrow','street stock is unstable around main terminals'],Manchester:['student demand is active','north west routes are moving bulk supply','police attention is up around the city centre'],Birmingham:['Midlands supply lines are moving fast','BHX traffic is drawing attention','prices are volatile after a quiet week'],Liverpool:['port rumours are moving the market','nightlife demand is lifting weekend prices','cheap stock is appearing near the docks'],Leeds:['student demand is lifting party stock','supply is moving through west Yorkshire','street prices look soft today'],Newcastle:['nightlife demand is strong','scarce stock is moving north','airport movement is quiet'],Bristol:['south west supply is tightening','festival demand is moving prices','police heat is low for now'],Cardiff:['weekend demand is rising','stock looks thin across the centre','cheap supply is rumoured near the docks'],Glasgow:['city centre demand is volatile','bulk supply is moving through Scotland','police pressure is unpredictable'],Edinburgh:['tourist demand is lifting prices','festival rumours are affecting stock','street supply is tight'],Aberdeen:['remote supply makes prices unpredictable','oil money is lifting demand','stock may be scarce tomorrow'],Belfast:['port movement is changing supply','police heat is rising','market demand is uneven'],Dublin:['airport movement is busy','city centre demand is strong','rumours suggest supply pressure'],Cork:['port supply is inconsistent','prices may soften tomorrow','local demand is quiet']}[city]||['market intelligence is unclear']; return pick(lines);}
function newRumour(){let r={drug:pickDrug(),type:Math.random()<.5?'scarce':'abundant',accuracy:rand(15,85)}; s.rumour=r; return r}
function rumourHtml(){let r=s.rumour||newRumour(); return `<strong>Market note:</strong> ${r.drug} may be ${r.type==='scarce'?'scarce and more expensive':'abundant and cheaper'} tomorrow. Source confidence: <strong>${r.accuracy}%</strong>.`}
function draw(){let p=places[s.city]; $('dayCount').textContent=s.day; $('cash').textContent=money(s.cash); $('bank').textContent=money(s.bank); $('debt').textContent=money(s.debt); $('health').textContent=Math.round(s.health)+'%'; $('healthBar').style.width=Math.max(0,s.health)+'%'; $('city').textContent=p[0]; $('country').textContent=p[1]+' · '+p[3]; $('flag').textContent=p[2]; $('marketInfo').innerHTML=`${p[0]}: ${cityText()}.<br>${rumourHtml()}`; $('noticeText').textContent=s.notice; $('spaceLabel').textContent=`${used()}/${totalSpace()}`; $('statusLocation').textContent=p[0]+', '+p[1]; $('rank').textContent=rank(); $('space').textContent=`${used()}/${totalSpace()}`; $('heat').textContent=s.heat+'%';
$('marketTable').innerHTML='<div class="row header"><span>Drug</span><span>Qty</span><span>Price</span><span>Trend</span></div>'+drugs.map(([name,icon])=>`<div class="row"><span class="drug"><b>${icon}</b>${name}</span><span>${s.supply[name]}</span><span class="price ${s.trends[name]?'':'down'}">${money(s.prices[name]||0)}</span><span class="trend ${s.trends[name]?'up':'down'}">${s.trends[name]?'↑':'↓'}</span></div>`).join('');
let items=Object.entries(s.inv).filter(([,q])=>q>0); $('pocketTable').innerHTML='<div class="row header"><span>Drug</span><span>Qty</span><span>Value</span></div>'+(items.length?items.map(([k,v])=>`<div class="row"><span>${k}</span><span>${v}</span><span>${money(v*s.prices[k])}</span></div>`).join(''):`<div class="row"><span>Empty</span><span>0</span><span>${money(0)}</span></div>`);}
function modal(t,h){$('modalTitle').textContent=t; $('modalBody').innerHTML=h; if(!$('modal').open)$('modal').showModal();}
function newGame(showLoans=false){s=baseState(); genPrices(); newRumour(); save(); draw(); if(showLoans) showLoanIntro();}
function showLoanIntro(){modal('Shady Loans',`<p class="subtle">You can start clean, but debt gives you buying power. These terms are deliberately bad and missed payments will hurt.</p><div class="loan-list">${lenders.map((l,i)=>`<button type="button" data-loan="${i}"><strong>${l[0]}</strong><br>up to ${money(l[1])} · ${l[3]*100}% interest · due in ${l[2]} days</button>`).join('')}</div><button type="button" id="skipLoan">Start without debt</button>`); setTimeout(()=>{document.querySelectorAll('[data-loan]').forEach(b=>b.onclick=()=>chooseLoan(+b.dataset.loan)); $('skipLoan').onclick=()=>$('modal').close();},0)}
function chooseLoan(i){let l=lenders[i]; modal(l[0],`<p>Borrow up to ${money(l[1])}. Repay ${l[3]*100}% interest by day ${s.day+l[2]}.</p><input id="loanAmount" type="number" min="1" max="${l[1]}" placeholder="Amount"><button type="button" class="sell" id="confirmLoan">ARE YOU SURE?</button>`); setTimeout(()=>$('confirmLoan').onclick=()=>{let amt=Math.min(+$('loanAmount').value||0,l[1]); if(!amt)return; let repay=Math.round(amt*(1+l[3])); s.cash+=amt; s.debt+=repay; s.loans.push({name:l[0],due:s.day+l[2],repay}); s.notice=`Borrowed ${money(amt)} from ${l[0]}. ${money(repay)} due day ${s.day+l[2]}.`; $('modal').close(); save(); draw();},0)}
function transact(type){modal(type,`<select id="drugSel">${drugs.map(d=>`<option>${d[0]}</option>`).join('')}</select><input id="qtySel" type="number" min="1" placeholder="Quantity"><button type="button" class="${type==='Buy'?'buy':'sell'}" id="doTrans">${type}</button>`); setTimeout(()=>$('doTrans').onclick=()=>{let d=$('drugSel').value,q=+$('qtySel').value||0;if(type==='Buy'){q=Math.min(q,totalSpace()-used(),Math.floor(s.cash/s.prices[d]),s.supply[d]); if(q<1)return; s.cash-=q*s.prices[d]; s.inv[d]+=q; s.supply[d]-=q; s.notice=`Bought ${q} units of ${d}.`;}else{q=Math.min(q,s.inv[d]); if(q<1)return; s.cash+=q*s.prices[d]; s.inv[d]-=q; s.notice=`Sold ${q} units of ${d}.`;} $('modal').close(); save(); draw();},0)}
function bank(){let openLoans=s.loans.length?s.loans.map(l=>`<div class="loan-row"><div><span>${l.name}</span><strong>${money(l.repay)} due day ${l.due}</strong></div><button type="button" data-payloan="${l.name}|${l.due}|${l.repay}">Pay</button></div>`).join(''):'<p class="subtle">No active loans.</p>'; modal('Bank',`<p class="subtle">Bank balance only changes when you deposit or withdraw.</p><input id="amount" type="number" placeholder="Amount"><button type="button" id="deposit">Deposit</button><button type="button" id="withdraw">Withdraw</button><button type="button" id="payDebt">Pay General Debt</button><h4>Loans</h4>${openLoans}<div class="loan-list">${lenders.map((l,i)=>`<button type="button" data-loan="${i}"><strong>${l[0]}</strong><br>Borrow up to ${money(l[1])} · ${l[3]*100}% interest · due in ${l[2]} days</button>`).join('')}</div>`); setTimeout(()=>{let amt=()=>+$('amount').value||0; $('deposit').onclick=()=>{let a=Math.min(amt(),s.cash);s.cash-=a;s.bank+=a;done()}; $('withdraw').onclick=()=>{let a=Math.min(amt(),s.bank);s.bank-=a;s.cash+=a;done()}; $('payDebt').onclick=()=>{let a=Math.min(amt(),s.cash,s.debt);s.cash-=a;s.debt-=a;done()}; document.querySelectorAll('[data-loan]').forEach(b=>b.onclick=()=>chooseLoan(+b.dataset.loan)); document.querySelectorAll('[data-payloan]').forEach(b=>b.onclick=()=>paySpecificLoan(b.dataset.payloan));},0)}

function paySpecificLoan(token){let [name,due,repay]=token.split('|'), amount=+repay; if(s.cash<amount){s.notice=`You need ${money(amount)} cash to clear ${name}.`; done(); return;} let idx=s.loans.findIndex(l=>l.name===name&&String(l.due)===String(due)&&String(l.repay)===String(repay)); if(idx<0)return; s.cash-=amount; s.debt=Math.max(0,s.debt-amount); s.notice=`Paid ${name}. Loan cleared.`; s.loans.splice(idx,1); done();}
function shop(){modal('Shop',`<h4>Storage</h4>${shopItems.map((it,i)=>`<button type="button" data-shop="${i}" ${s.owned.includes(it[0])?'disabled':''}>${it[0]} · ${money(it[1])} · 0/${it[2]}</button>`).join('')}<h4>Weapons</h4><p class="muted">Weapons help in fights but are lost when flying.</p>${weapons.map((w,i)=>`<button type="button" data-weapon="${i}">${w[0]} · ${money(w[1])}</button>`).join('')}`); setTimeout(()=>{document.querySelectorAll('[data-shop]').forEach(b=>b.onclick=()=>{let it=shopItems[+b.dataset.shop]; if(s.cash<it[1])return; s.cash-=it[1]; s.owned.push(it[0]); s.notice=`Bought ${it[0]}. Storage increased by ${it[2]}.`; done();}); document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>{let w=weapons[+b.dataset.weapon]; if(s.cash<w[1])return; s.cash-=w[1]; if(!s.weapons.includes(w[0]))s.weapons.push(w[0]); s.notice=`Bought ${w[0]}.`; done();});},0)}
function dump(){let items=Object.entries(s.inv).filter(([,q])=>q>0); modal('Dump Stock',items.length?items.map(([k])=>`<button type="button" data-dump="${k}">${k}</button>`).join(''):'<p>Your storage is empty.</p>'); setTimeout(()=>document.querySelectorAll('[data-dump]').forEach(b=>b.onclick=()=>{s.notice=`Dumped ${s.inv[b.dataset.dump]} units of ${b.dataset.dump}.`;s.inv[b.dataset.dump]=0;done();}),0)}
function done(){if($('modal').open)$('modal').close(); save(); draw()}
function stay(){nextDay(`You stay in ${places[s.city][0]}.`,true)}
function travel(){modal('Travel',`<p class="subtle">Select a UK or Ireland city. Weapons are lost before boarding.</p><div class="travel-list">${places.map((p,i)=>`<button type="button" data-city="${i}">${p[2]} <strong>${p[0]}</strong> · ${p[1]} · ${p[3]}</button>`).join('')}</div>`); setTimeout(()=>document.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{s.city=+b.dataset.city; s.weapons=[]; $('modal').close(); nextDay(`You land in ${places[s.city][0]}. Weapons were lost before boarding.`,false);}),0)}
function debtReminderHtml(){if(!s.loans.length)return '<p class="subtle">No active loan debt.</p>'; return '<div class="debt-reminder"><strong>DEBT REMINDER</strong>'+s.loans.map(l=>{let days=l.due-s.day; let dueText=days>0?`due in ${days} day${days===1?'':'s'}`:'DUE NOW'; return `<div><span>${l.name}</span><b>${money(l.repay)}</b><em>${dueText}</em></div>`}).join('')+'</div>'}
function nextDay(base,showRumour){let old={rumour:s.rumour,true:Math.random()*100<s.rumour.accuracy}; s.day++; s.debt=Math.round(s.debt*1.02); s.heat=Math.min(100,Math.max(0,s.heat+rand(-8,13))); genPrices(old); newRumour(); randomEvent(base); if(s.day>s.maxDay)return endGame(); save(); draw(); let rumourBlock=showRumour?`<h4>Rumour Result</h4><p><strong>${old.true?'TRUE':'FALSE'}</strong> · ${old.rumour.drug} was tipped to become ${old.rumour.type==='scarce'?'scarce and more expensive':'abundant and cheaper'}.</p><p>Source confidence was ${old.rumour.accuracy}%.</p>`:''; modal(showRumour?'Stay Here':'Travel Result',`<p>${s.notice}</p>${rumourBlock}<h4>Loan Status</h4>${debtReminderHtml()}<button type="button" id="continueEvent">Continue</button>`); setTimeout(()=>$('continueEvent').onclick=()=>{$('modal').close();handleDueLoans();},0);}
function handleDueLoans(){let due=s.loans.filter(l=>l.due<=s.day); if(!due.length){maybeFight();return;} modal('DEBT DUE',`<p class="subtle">Your lender wants payment today. Pay it now or the balance rises by 25%, your health drops by 15%, and the same debt is chased again tomorrow.</p>${due.map((l,i)=>`<div class="loan-row"><div><span>${l.name}</span><strong>${money(l.repay)} due now</strong></div><button type="button" data-duepay="${i}">PAY OFF DEBT</button></div>`).join('')}<button type="button" class="sell" id="missDebt">Do not pay</button>`); setTimeout(()=>{document.querySelectorAll('[data-duepay]').forEach(b=>b.onclick=()=>payDueLoan(due[+b.dataset.duepay])); $('missDebt').onclick=missDueLoans;},0)}
function payDueLoan(loan){if(s.cash<loan.repay){s.notice=`You need ${money(loan.repay)} cash to pay ${loan.name}.`; save(); draw(); handleDueLoans(); return;} let idx=s.loans.indexOf(loan); if(idx<0)return; s.cash-=loan.repay; s.debt=Math.max(0,s.debt-loan.repay); s.notice=`Paid ${loan.name}. Loan cleared.`; s.loans.splice(idx,1); save(); draw(); $('modal').close(); handleDueLoans();}
function missDueLoans(){let due=s.loans.filter(l=>l.due<=s.day); let added=0; due.forEach(l=>{let old=l.repay; l.repay=Math.round(l.repay*1.25); added+=l.repay-old; l.due=s.day+1;}); s.debt+=added; s.health=Math.max(1,s.health-15); s.heat=Math.min(100,s.heat+10); s.notice=`Debt unpaid. You are roughed up, health drops 15%, and the debt increases by ${money(added)}.`; save(); draw(); $('modal').close(); maybeFight();}
function checkLoans(){}
function takeDrugs(maxPct, personOnly=false){let capacity=personOnly?personSpace():totalSpace(), ratio=Math.min(1, capacity/Math.max(1,totalSpace())), stolen=[]; Object.entries(s.inv).forEach(([k,v])=>{let q=Math.floor(v*(rand(10,maxPct)/100)*(personOnly?ratio:1)); if(q>0){s.inv[k]-=q; stolen.push(`${q} ${k}`)}}); return stolen;}
function randomEvent(base){let roll=Math.random(),d=pickDrug(); s.notice=base+' '; if(roll<.14){let pct=rand(10,65),lost=Math.floor(s.cash*pct/100),stolen=takeDrugs(35); s.cash-=lost; s.health=Math.max(5,s.health-rand(3,15)); s.notice+=`You are mugged. ${pct}% of your cash is taken (${money(lost)}). ${stolen.length?'Stock stolen: '+stolen.join(', ')+'.':'No stock was taken.'}`;} else if(roll<.24){let q=Math.min(rand(5,80),totalSpace()-used()); if(q>0)s.inv[d]+=q; s.notice+=`A contact gives you ${q} units of ${d}.`;} else if(roll<.36){s.prices[d]*=rand(2,4); s.notice+=`${d} is drying up. Prices spike.`;} else if(roll<.48){s.prices[d]=Math.max(1,Math.round(s.prices[d]*.35)); s.supply[d]+=rand(100,500); s.notice+=`The market is flooded with ${d}. Prices collapse.`;} else if(roll<.60){s.heat=Math.min(100,s.heat+rand(10,25)); s.notice+='Police are visible near transport hubs. Heat rises.';} else s.notice+='A quiet day. The market holds.';}
function attacker(){let r=Math.random(),a=0; for(let x of attackers){a+=x[1]; if(r<a)return x} return attackers.at(-1)}
function bestWeapon(){return s.weapons.includes('Handgun')?weapons[2]:s.weapons.includes('Machete')?weapons[1]:s.weapons.includes('Small Knife')?weapons[0]:null}
function maybeFight(){if(Math.random()>=.20)return; let a=attacker(); s.currentFight={name:a[0],damage:a[2],lootPct:a[3]}; modal('Trouble',`<p>You are confronted by a <strong>${a[0]}</strong>.</p><p>Outcome depends on the threat level and whether you have a weapon.</p><button type="button" id="surrenderBtn">Surrender</button><button type="button" id="runBtn">Run</button><button type="button" class="sell" id="fightBtn">Fight</button>`); setTimeout(()=>{$('surrenderBtn').onclick=()=>resolveFight('surrender');$('runBtn').onclick=()=>resolveFight('run');$('fightBtn').onclick=()=>resolveFight('fight');},0)}
function resolveFight(choice){let f=s.currentFight, w=bestWeapon(),msg=''; if(choice==='surrender'){let lost=s.cash; s.cash=0; let stolen=takeDrugs(100,true); msg=`You surrender to the ${f.name}. You lose all cash and stock carried on you. ${stolen.length?'Taken: '+stolen.join(', ')+'.':'No stock was on you.'}`;} if(choice==='run'){let chance=.5+(w?w[2]:0), ok=Math.random()<chance; if(ok){msg=`You run from the ${f.name} and get away${w?' using your '+w[0]+' to create distance':''}.`; s.heat=Math.min(100,s.heat+rand(1,6));}else{let lost=Math.floor(s.cash*f.lootPct); s.cash-=lost; s.health=Math.max(1,s.health-f.damage); let stolen=takeDrugs(35,true); msg=`You fail to get away from the ${f.name}. Health drops ${f.damage}%. You lose ${money(lost)}${stolen.length?' and '+stolen.join(', '):''}.`;}} if(choice==='fight'){let chance=w?(f.name==='single addict'?0.75:Math.min(.9,.10+w[2])):.25; let win=Math.random()<chance; if(win){let gain=rand(25,250)*(w?2:1); s.cash+=gain; msg=`You fight the ${f.name} and win. ${w?'Your '+w[0]+' makes the difference.':'No weapon, but you get lucky.'} You take ${money(gain)}.`; s.heat=Math.min(100,s.heat+rand(5,15));}else{let dmg=w?Math.max(1,Math.round(f.damage*(1-w[2]))):f.damage; let lost=Math.floor(s.cash*f.lootPct); s.cash-=lost; s.health=Math.max(1,s.health-dmg); let stolen=takeDrugs(45,true); msg=`You fight the ${f.name} and lose. Health drops ${dmg}%. You lose ${money(lost)}${stolen.length?' and '+stolen.join(', '):''}.`;}} s.notice=msg; s.currentFight=null; done();}
function endGame(){let score=s.cash+s.bank+Object.entries(s.inv).reduce((a,[k,v])=>a+v*s.prices[k],0)-s.debt; modal('Game Over',`<p>Final net worth: <strong>${money(score)}</strong></p><p>Rank: <strong>${rank()}</strong></p><button type="button" id="again">New Game</button>`); setTimeout(()=>$('again').onclick=()=>{newGame();},0)}
function save(){localStorage.setItem('noir_market_v6',JSON.stringify(s))} function load(){let x=localStorage.getItem('noir_market_v6')||localStorage.getItem('noir_market_v5')||localStorage.getItem('noir_market_v4'); if(x){s=JSON.parse(x);draw();return false;} newGame(false);return true;}
function particles(){
  const holder=$('particle-canvas');
  const canvas=document.createElement('canvas');
  const ctx=canvas.getContext('2d');
  holder.innerHTML='';
  holder.appendChild(canvas);
  let particles=[], mouse={x:null,y:null,active:false};
  function resize(){
    canvas.width=holder.offsetWidth*devicePixelRatio;
    canvas.height=holder.offsetHeight*devicePixelRatio;
    canvas.style.width=holder.offsetWidth+'px';
    canvas.style.height=holder.offsetHeight+'px';
    const count=Math.max(55,Math.floor((holder.offsetWidth*holder.offsetHeight)/8500));
    particles=Array.from({length:count},()=>({
      x:Math.random()*canvas.width,
      y:Math.random()*canvas.height,
      vx:(Math.random()-.5)*0.34*devicePixelRatio,
      vy:(Math.random()-.5)*0.34*devicePixelRatio,
      r:(1+Math.random()*1.7)*devicePixelRatio
    }));
  }
  function point(e){const r=canvas.getBoundingClientRect(); mouse.x=(e.clientX-r.left)*devicePixelRatio; mouse.y=(e.clientY-r.top)*devicePixelRatio; mouse.active=true}
  holder.addEventListener('mousemove',point);
  holder.addEventListener('touchmove',e=>{if(e.touches[0])point(e.touches[0])},{passive:true});
  holder.addEventListener('mouseleave',()=>mouse.active=false);
  addEventListener('resize',resize); resize();
  function loop(){
    ctx.clearRect(0,0,canvas.width,canvas.height);
    const all=mouse.active?[...particles,{x:mouse.x,y:mouse.y,vx:0,vy:0,r:2*devicePixelRatio,mouse:true}]:particles;
    for(const p of particles){
      p.x+=p.vx; p.y+=p.vy;
      if(p.x<0||p.x>canvas.width)p.vx*=-1;
      if(p.y<0||p.y>canvas.height)p.vy*=-1;
    }
    for(let i=0;i<all.length;i++){
      const a=all[i];
      ctx.beginPath();ctx.fillStyle=a.mouse?'rgba(255,255,255,.26)':'rgba(255,255,255,.17)';ctx.arc(a.x,a.y,a.r,0,Math.PI*2);ctx.fill();
      for(let j=i+1;j<all.length;j++){
        const b=all[j], dx=a.x-b.x, dy=a.y-b.y, d=Math.sqrt(dx*dx+dy*dy), max=125*devicePixelRatio;
        if(d<max){ctx.beginPath();ctx.strokeStyle=`rgba(255,255,255,${(1-d/max)*.16})`;ctx.lineWidth=.7*devicePixelRatio;ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
      }
    }
    requestAnimationFrame(loop);
  }
  loop();
}
function setupTilt(){let splash=$('splash');function setTilt(x,y){let px=Math.max(-18,Math.min(18,x*.8)),py=Math.max(-9,Math.min(9,y*.35));splash.style.setProperty('--tilt-x',(x*.55)+'deg');splash.style.setProperty('--tilt-y',(-y*.35)+'deg');splash.style.setProperty('--powder-x',px+'px');splash.style.setProperty('--powder-y',py+'px');splash.style.setProperty('--powder-r',(x*.35)+'deg')} window.addEventListener('deviceorientation',e=>{setTilt(e.gamma||0,e.beta||0)},true); window.addEventListener('mousemove',e=>{let x=(e.clientX/innerWidth-.5)*18,y=(e.clientY/innerHeight-.5)*18;setTilt(x,y)})}
$('buyBtn').onclick=()=>transact('Buy'); $('sellBtn').onclick=()=>transact('Sell'); $('stayBtn').onclick=stay; $('travelBtn').onclick=travel; $('bankBtn').onclick=bank; $('dumpBtn').onclick=dump; $('shopBtn').onclick=shop; $('newGameBtn').onclick=()=>newGame(true); let firstFreshGame=false; $('splash').onclick=()=>{$('splash').classList.add('hide'); setTimeout(()=>{if(firstFreshGame)showLoanIntro();},460)}; particles(); setupTilt(); firstFreshGame=load();
